main: de.timesnake.extension.decoration.main.ExDecoration
version: 1.2.1
name: extension-decoration
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  decoration:
    aliases:
      - deco
      - decos
      - decorations
     