main: de.timesnake.extension.decoration.main.ExDecoration
version: ${version}
name: extension-decoration
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  decoration:
    aliases:
      - deco
      - decos
      - decorations
     