main: de.timesnake.extension.decoration.main.ExDecoration
version: 1.0
name: extension-decoration
author: Mn
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  deco:
  decoration:
  decos:
  decorations:
     